// Shared micro-benchmark harness: no dependencies, warmup + timed loop
// plus gc-gated heap deltas. Run with:
//   node --expose-gc --experimental-strip-types bench/<name>.bench.ts
// Heap numbers are approximate (GC/allocator noise); use them for relative
// before/after comparisons on the same machine, not absolute claims.

export interface Timing {
  iterations: number;
  totalMs: number;
  meanNs: number;
  opsPerSec: number;
}

export function measure(fn: () => void, iterations: number): Timing {
  const warmup = Math.min(5_000, iterations);
  for (let i = 0; i < warmup; i += 1) fn();
  const start = performance.now();
  for (let i = 0; i < iterations; i += 1) fn();
  const totalMs = performance.now() - start;
  const meanNs = (totalMs / iterations) * 1e6;
  return { iterations, totalMs, meanNs, opsPerSec: 1e9 / meanNs };
}

/**
 * Garbage generated by `runs` executions: gc, snapshot, run with NO gc in
 * between, snapshot again. The pre-gc delta approximates short-lived
 * garbage volume (comparative only); the post-gc delta must stay ~0 or
 * the benchmark itself is retaining results (a leak in the harness, or a
 * real leak in the code under test).
 */
export function garbageBytes(
  fn: () => void,
  runs: number,
  rounds = 7,
): { generatedPerOp: number; retained: number } {
  const gc = (globalThis as { gc?: () => void }).gc;
  if (!gc) throw new Error("run node with --expose-gc for heap measurements");
  const samples: number[] = [];
  let retained = 0;
  for (let r = 0; r < rounds; r += 1) {
    gc();
    const before = process.memoryUsage().heapUsed;
    for (let i = 0; i < runs; i += 1) fn();
    samples.push((process.memoryUsage().heapUsed - before) / runs);
    gc();
    retained = process.memoryUsage().heapUsed - before;
  }
  samples.sort((a, b) => a - b);
  return { generatedPerOp: samples[rounds >> 1], retained };
}

export function fmtTiming(t: Timing): string {
  return (
    `${t.iterations.toLocaleString("en-US")} iters in ` +
    `${t.totalMs.toFixed(1)}ms | ` +
    `${t.opsPerSec.toLocaleString("en-US", { maximumFractionDigits: 0 })} ops/sec | ` +
    `${t.meanNs.toFixed(0)}ns/op`
  );
}

export function benchHeader(title: string): void {
  console.log(`\n=== ${title} ===`);
  console.log(`node ${process.version} ${process.arch}`);
}

/** Awaited variant of measure for async pipelines. */
export async function measureAsync(
  fn: () => Promise<unknown>,
  iterations: number,
): Promise<Timing> {
  const warmup = Math.min(200, iterations);
  for (let i = 0; i < warmup; i += 1) await fn();
  const start = performance.now();
  for (let i = 0; i < iterations; i += 1) await fn();
  const totalMs = performance.now() - start;
  const meanNs = (totalMs / iterations) * 1e6;
  return { iterations, totalMs, meanNs, opsPerSec: 1e9 / meanNs };
}

/** Awaited variant of garbageBytes: every iteration settles before sampling. */
export async function garbageBytesAsync(
  fn: () => Promise<unknown>,
  runs: number,
  rounds = 7,
): Promise<{ generatedPerOp: number; retained: number }> {
  const gc = (globalThis as { gc?: () => void }).gc;
  if (!gc) throw new Error("run node with --expose-gc for heap measurements");
  const samples: number[] = [];
  let retained = 0;
  for (let r = 0; r < rounds; r += 1) {
    gc();
    const before = process.memoryUsage().heapUsed;
    for (let i = 0; i < runs; i += 1) await fn();
    samples.push((process.memoryUsage().heapUsed - before) / runs);
    gc();
    retained = process.memoryUsage().heapUsed - before;
  }
  samples.sort((a, b) => a - b);
  return { generatedPerOp: samples[rounds >> 1], retained };
}
